### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by asom007** [booleanbites/houzi-rest-api#1]
Hello
I tried to add the plugin to the website. I got an error message, "Plugin could not be activated because it triggered a fatal error."

Can you please check for that?

**Comment by AdilSoomro** [comment]
Hi,

- what's your website address?
- does it show any line number in error?
- do you have an old plugin active before?

**Comment by AdilSoomro** [comment]
Hi, is there any update on this?

**Comment by AdilSoomro** [comment]
Hello, any update?

**Comment by petarmihaylov** [comment]
> Hi,
> 
> * what's your website address?
> * does it show any line number in error?
> * do you have an old plugin active before?

Hey @AdilSoomro ,

I have the same issue. I did have `v1.3.8` installed before, and I get the same error. 

No line number in the error:

![image](https://github.com/booleanbites/houzi-rest-api/assets/5885500/59030d93-d0eb-4e24-835b-f8aabf920bdd)


I can reinstall and activate `v1.3.8`, but cannot install `v1.3.8.1` even after completely removing `v1.3.8`.

**Comment by petarmihaylov** [comment]
I had to manually delete `v1.3.8` from the host server before I could install `v1.3.8.1`.

After I deleted the old version, the new one installed and activated.

**Comment by AdilSoomro** [comment]
As @petarmihaylov mentioned, if you already have an active copy of old version. please disable and delete the old and then attempt newer version install.
